### ISSUE TITLE
Add Google Analytics to documentation site

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/docs#80]
Related docs for Sphinx RTD theme: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-analytics_id

```py
html_theme_options = {
    'analytics_id': 'G-XXXXXXXXXX',
```

Related docs for Material for MkDocs theme: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

```yaml file=mkdocs.yaml
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```
